import LegalLayout from "../components/LegalLayout";

export const metadata = {
  title: "Terms of Service",
  description:
    "The terms and conditions for using TarotByte — account responsibilities, paid features, refunds, and the entertainment disclaimer.",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" subtitle="The rules of the reading room." lastUpdated="July 2025">
      <p>
        Welcome to TarotByte. These Terms of Service (&ldquo;Terms&rdquo;) govern your use of
        <a href="https://www.tarotbyte.app"> tarotbyte.app</a> and all related services (collectively, the
        &ldquo;Service&rdquo;). By creating an account or using any reading, you agree to these Terms. If you
        do not agree, please do not use the Service.
      </p>

      <div className="legal-callout">
        <p><strong>Important:</strong> TarotByte is an entertainment and reflection product. Our readings are not professional advice — not medical, legal, financial, psychological, or otherwise. Always consult a qualified professional for important decisions.</p>
      </div>

      <h2>1. Eligibility</h2>
      <p>You must be at least 13 years old (or the minimum age of digital consent in your jurisdiction) to create an account. By using the Service, you represent that you meet this requirement and are legally able to enter into these Terms.</p>

      <h2>2. Your Account</h2>
      <p>You are responsible for maintaining the confidentiality of your password and for all activity under your account. You agree to notify us immediately of any unauthorized use. You may not share, sell, or transfer your account to another person. We may suspend or terminate accounts that violate these Terms or that we believe are engaged in fraudulent or abusive activity.</p>

      <h2>3. The Service &amp; Readings</h2>
      <p>TarotByte offers free and paid tarot readings. Free readings (such as Yes/No and Past·Present·Future) are available without an account. The Energy Reading and the Astral Threads layer require a free membership. The Decan Engine (the deepest interpretive layer) is available through subscription or à la carte add-on credits.</p>
      <p>Readings are generated by our proprietary engine, which combines traditional tarot meanings with our original astrology-based interpretive system (the Astral Threads deck and the Decan Engine). While we strive for thoughtful, meaningful interpretations, readings are subjective, creative content and should be treated as such.</p>

      <h2>4. Paid Features &amp; Billing</h2>

      <h3>Subscriptions</h3>
      <p>We offer a monthly subscription at $6.99/month and an annual subscription at $49/year. Subscriptions renew automatically until canceled. You can cancel at any time from your account or by contacting us; cancellation stops future renewals but does not refund the current billing period. Subscription pricing may change with reasonable advance notice; existing subscribers will be charged the then-current rate upon renewal.</p>

      <h3>Decan Engine add-ons</h3>
      <p>Members may purchase individual Decan Engine readings at $2 each (member price), $4 list price, or in a $5 three-credit pack. Members also receive one free Decan Engine add-on per month, which does not roll over. Purchased credits do not expire while your account is active.</p>

      <h3>Payment processing</h3>
      <p>All payments are processed by Stripe. We do not store your full card details. By making a purchase, you authorize Stripe to charge your selected payment method for the stated amount.</p>

      <h2>5. Refund Policy</h2>
      <p>Because readings are instantly delivered digital content, add-on credits and one-time purchases are generally non-refundable. However, we want you to be satisfied. If you experience a technical failure that prevents you from using a purchased reading or credit, contact us at <a href="mailto:hello@tarotbyte.app">hello@tarotbyte.app</a> within 14 days and we will review your case. Subscription refunds are handled on a case-by-case basis; if you cancel within 7 days of your first subscription charge and have not used paid features, we may issue a full refund. This does not affect your statutory rights where applicable.</p>

      <h2>6. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose or in violation of these Terms</li>
        <li>Attempt to access accounts, data, or systems you are not authorized to access</li>
        <li>Interfere with or disrupt the Service, its servers, or its security measures</li>
        <li>Reverse engineer, decompile, or attempt to extract the source code or proprietary algorithms (including the Decan Engine and Astral Threads systems)</li>
        <li>Scrape, crawl, or systematically collect readings or content from the Service</li>
        <li>Use automated scripts, bots, or tools to generate readings at scale without our permission</li>
        <li>Reproduce, redistribute, or resell our readings or content without written permission</li>
      </ul>

      <h2>7. Intellectual Property</h2>
      <p>The Service, including its readings, the Astral Threads deck, the Decan Engine system, card artwork, decan titles, text, graphics, logos, and software, is the property of TarotByte and is protected by copyright, trademark, and other intellectual property laws. The individual decan titles (such as &ldquo;The First Move,&rdquo; &ldquo;The Kept Promise&rdquo;) are original TarotByte creations.</p>
      <p>You may use readings for personal, non-commercial reflection. You may screenshot or share a single reading for personal social media use, provided you do not remove attribution or imply endorsement. Any commercial use, redistribution, or derivative work requires our written permission.</p>

      <h2>8. User-Generated Content</h2>
      <p>The questions you submit during readings are your own content. You retain ownership of your questions. By submitting a question, you grant us a limited license to process it to generate and store your reading. We do not review individual questions and are not responsible for their content. Please do not submit sensitive personal information (such as Social Security numbers, financial account details, or health information) in your reading questions.</p>

      <h2>9. Disclaimers</h2>
      <p><strong>The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,</strong> express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or secure, or that readings will be accurate, reliable, or applicable to your life.</p>
      <p><strong>Readings are for entertainment and reflection purposes only.</strong> They are not a substitute for professional advice of any kind — medical, psychological, legal, financial, or spiritual. You are solely responsible for any decisions you make based on or influenced by a reading. TarotByte and its readings should not be relied upon for important life decisions.</p>

      <h2>10. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, TarotByte and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, arising from your use of (or inability to use) the Service, even if we have been advised of the possibility of such damages. Our total liability for any claim arising from the Service shall not exceed the amount you have paid us in the 12 months preceding the claim, or $50, whichever is greater.</p>

      <h2>11. Indemnification</h2>
      <p>You agree to indemnify and hold harmless TarotByte and its operators from any claims, damages, liabilities, or expenses (including reasonable legal fees) arising from your use of the Service, your violation of these Terms, or your infringement of any third-party rights.</p>

      <h2>12. Termination</h2>
      <p>You may delete your account at any time. We may suspend or terminate your access to the Service at any time, with or without cause or notice, including for violations of these Terms. Upon termination, your right to use the Service ends immediately. Provisions that by their nature should survive termination (including intellectual property, disclaimers, and limitation of liability) will remain in effect.</p>

      <h2>13. Governing Law</h2>
      <p>These Terms are governed by the laws of the jurisdiction in which TarotByte operates, without regard to conflict-of-law principles. Any disputes arising from these Terms or the Service will be resolved in the competent courts of that jurisdiction, unless you are a consumer with mandatory rights to a different forum under local law.</p>

      <h2>14. Changes to These Terms</h2>
      <p>We may update these Terms from time to time. If we make material changes, we will notify you via email or a notice on the site. The &ldquo;last updated&rdquo; date above reflects the most recent revision. Continued use of TarotByte after changes take effect constitutes acceptance of the updated Terms.</p>

      <h2>15. Contact</h2>
      <p>If you have questions about these Terms, please contact us at <a href="mailto:hello@tarotbyte.app">hello@tarotbyte.app</a>.</p>
    </LegalLayout>
  );
}
