// TarotByte — "Radiant" Oracle Overlay
// ORIGINAL 12-sign celestial oracle deck. This is TarotByte's proprietary IP:
// original astrological "energy" cards used to CLARIFY a tarot draw.
// Concept is not protectable; this specific system + all text is TarotByte's own.
// Editable, launch-usable placeholder copy in a warm, energy-forward voice.

export const RADIANT_ORACLE = [
  { id: "aries", image: "/oracle/aries.png", sign: "Aries", element: "Fire", dates: "Mar 21 – Apr 19",
    keyword: "Ignition",
    energy: "A surge of raw initiative. This is the spark that starts — bold, direct, unafraid to be first.",
    clarifier: "Act on the impulse. The energy asks for courage, not more waiting." },
  { id: "taurus", image: "/oracle/taurus.png", sign: "Taurus", element: "Earth", dates: "Apr 20 – May 20",
    keyword: "Rooting",
    energy: "Grounded, sensual, patient. Value what lasts and let stability be its own reward.",
    clarifier: "Slow down and build. What you're tending needs steady hands, not speed." },
  { id: "gemini", image: "/oracle/gemini.png", sign: "Gemini", element: "Air", dates: "May 21 – Jun 20",
    keyword: "Exchange",
    energy: "Curiosity in motion — ideas, conversation, and the space between two truths.",
    clarifier: "Ask the question. Connection and information are the keys right now." },
  { id: "cancer", image: "/oracle/cancer.png", sign: "Cancer", element: "Water", dates: "Jun 21 – Jul 22",
    keyword: "Tending",
    energy: "Deep feeling and protective care. The tides of home, memory, and belonging.",
    clarifier: "Honor the emotion beneath the situation. Nurture what feels tender." },
  { id: "leo", image: "/oracle/leo.png", sign: "Leo", element: "Fire", dates: "Jul 23 – Aug 22",
    keyword: "Radiance",
    energy: "Warm, generous, and fully seen. The heart shining out with confident joy.",
    clarifier: "Step into the light. Express yourself boldly — you were meant to be witnessed." },
  { id: "virgo", image: "/oracle/virgo.png", sign: "Virgo", element: "Earth", dates: "Aug 23 – Sep 22",
    keyword: "Refining",
    energy: "Precise, devoted, and improving. The sacred art of care through the details.",
    clarifier: "Tend the small things. Order and service are the path forward." },
  { id: "libra", image: "/oracle/libra.png", sign: "Libra", element: "Air", dates: "Sep 23 – Oct 22",
    keyword: "Balancing",
    energy: "Harmony, fairness, and the beauty of the middle way. Relationship as a mirror.",
    clarifier: "Seek balance and honest partnership. Weigh both sides before you choose." },
  { id: "scorpio", image: "/oracle/scorpio.png", sign: "Scorpio", element: "Water", dates: "Oct 23 – Nov 21",
    keyword: "Alchemy",
    energy: "Intense, transformative depth. What is hidden rises to be transmuted.",
    clarifier: "Go beneath the surface. This is about power, truth, and rebirth." },
  { id: "sagittarius", image: "/oracle/sagittarius.png", sign: "Sagittarius", element: "Fire", dates: "Nov 22 – Dec 21",
    keyword: "Seeking",
    energy: "Expansive, optimistic, and free. The arrow aimed at meaning and horizon.",
    clarifier: "Widen your view. Adventure, faith, and the bigger picture call you." },
  { id: "capricorn", image: "/oracle/capricorn.png", sign: "Capricorn", element: "Earth", dates: "Dec 22 – Jan 19",
    keyword: "Ascending",
    energy: "Disciplined ambition and the long climb. Mastery earned one step at a time.",
    clarifier: "Commit to the plan. Structure and patience carry you to the summit." },
  { id: "aquarius", image: "/oracle/aquarius.png", sign: "Aquarius", element: "Air", dates: "Jan 20 – Feb 18",
    keyword: "Awakening",
    energy: "Inventive, independent, future-facing. The vision that breaks the mold.",
    clarifier: "Trust your originality. The unconventional path is the true one here." },
  { id: "pisces", image: "/oracle/pisces.png", sign: "Pisces", element: "Water", dates: "Feb 19 – Mar 20",
    keyword: "Dreaming",
    energy: "Boundless intuition and compassion. The dissolve between self and everything.",
    clarifier: "Follow the dream and the feeling. Surrender to what the soul already knows." },
];

export default RADIANT_ORACLE;
